### PR TITLE
Accessibility section

### PR DESCRIPTION
**Pull request by espinr**
Closes: #35 

Informative section on accessibility considerations. It includes generic information and recommendations for user agents, based on the UAAG 2.0. 

Commit message:
New accessibility section

***
<a href="https://pr-preview.s3.amazonaws.com/espinr/miniapp-packaging/pull/44.html" title="Last updated on Dec 21, 2021, 3:04 PM UTC (4fc7e46)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/miniapp-packaging/44/533fa40...espinr:4fc7e46.html" title="Last updated on Dec 21, 2021, 3:04 PM UTC (4fc7e46)">Diff</a>

### CODE REVIEW

**Comment by espinr** [comment]
Preview at https://raw.githack.com/espinr/miniapp-packaging/a11y-section/index.html#sec-accessibility

**Review by xfq — APPROVED** [review]
LGTM. Thank you!

**Comment by Sharonzd** [comment]
It looks good to me, too.

**Comment by espinr** [comment]
No objections received during the [meeting on 20th Jan](https://www.w3.org/2022/01/20-miniapp-minutes.html).

**Pull request merged**
